/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.0
 * $ pg-to-ts generate -c postgres://username:password@localhost:5432/example -t users -s public
 *
 */


export type Json = unknown;

// Table users
export interface Users {
  id: number;
  balance: number | null;
}
export interface UsersInput {
  id?: number;
  balance?: number | null;
}
const users = {
  tableName: 'users',
  columns: ['id', 'balance'],
  requiredForInsert: [],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Users,
  $input: null as unknown as UsersInput
} as const;


export interface TableTypes {
  users: {
    select: Users;
    input: UsersInput;
  };
}

export const tables = {
  users,
}
